language: objective-c
osx_image: xcode9.3
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install xcpretty
script:
  - pod repo update
  - pod spec lint --allow-warnings
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - nilit.danan@kaltura.com
    on_success: change
    on_failure: always
